### ISSUE TITLE
error when schema uses property 'keys'

### ISSUE THREAD

**Issue by kapilt** [horejsek/python-fastjsonschema#46]
The internal code gen creates variables based on the property name but in a few cases this can conflict with the internal booking variable names.

here's a snippet from poking around in pdb on a generated file

```python
89589           data_keys = set(data.keys())
89590           if "type" in data_keys:
89591               data_keys.remove("type")
89592               data_type = data["type"]
89593               if data_type not in ['progagated-tags', 'propagated-tags']:
89594                   raise JsonSchemaException("data.type must be one of ['progagated-tags', 'propagated-tags']")
89595           if "keys" in data_keys:
89596               data_keys.remove("keys")
89597               data_keys = data["keys"]
89598               if not isinstance(data_keys, (list)):
89599                   raise JsonSchemaException("data.keys must be array")
```

the data in this case was
```python
{'keys': ['ABC', 'BCD'],
 'match': False,
 'propagate': True,
 'type': 'propagated-tags'}
```

and the relevant schema snippet

```yaml
properties:
  keys:
    items:
      type: string
    type: array
  match:
    type: boolean
  propagate:
    type: boolean
  type:
    enum:
    - progagated-tags
    - propagated-tags
required:
 - type
```
