### ISSUE TITLE
bad code gen for integer with exclusiveMinimum/exclusiveMaximum

### ISSUE THREAD

**Issue by kapilt** [horejsek/python-fastjsonschema#47]
Given a schema like

```yaml
properties:
  period:
    exclusiveMaximum: true
    exclusiveMinimum: true
    maximum: 1209600
    minimum: 60
    type: integer
  type:
    enum:
    - set-retention-period
required:
- type
```

the generated code includes this clause for period

```python
        if "period" in data_keys:
            data_keys.remove("period")
            data_period = data["period"]
            if not isinstance(data_period, (int)) and not (isinstance(data_period, float) and data_period.is_integer()) or isinstance(data_period, bool):
                raise JsonSchemaException("data.period must be integer")
            if isinstance(data_period, (int, float)):
                if data_period <= 60:
                    raise JsonSchemaException("data.period must be bigger than 60")
            if isinstance(data_period, (int, float)):
                if data_period >= 1209600:
                    raise JsonSchemaException("data.period must be smaller than 1209600")
            if isinstance(data_period, (int, float)):
                if data_period <= True:
                    raise JsonSchemaException("data.period must be bigger than True")
            if isinstance(data_period, (int, float)):
                if data_period >= True:
                    raise JsonSchemaException("data.period must be smaller than True")
```

the bottom two comparison checks shouldn't be there, ie there's no reason to be comparing this to the integer value of `True`.
